items:
    recent_issues:
        template: OroAcademyIssueTrackerBundle:Issue:recentIssues.html.twig
        applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)'
    add_issue_button:
        template: OroAcademyIssueTrackerBundle:Issue:createButton.html.twig
        applicable: '@oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)'

placeholders:
    view_content_data_additional_information:
        items:
            recent_issues:
                order: 100
    view_navButtons_before:
        items:
            add_issue_button:
                order: 100
