items:
    recent_issues:
        template: OroAcademyIssueTrackerBundle:Issue:recentIssues.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)

placeholders:
    view_content_data_additional_information:
        items:
            recent_issues:
                order: 100
